begin;
create extension if not exists pg_cron;
create extension if not exists pg_net;
create table if not exists public.arise_push_deliveries(
 id bigint generated by default as identity primary key,
 subscription_id bigint not null references public.push_subscriptions(id),
 delivery_date date not null, slot text not null check(slot in ('morning','evening')),
 status text not null default 'processing' check(status in ('processing','sent','failed','expired')),
 created_at timestamptz not null default now(),finished_at timestamptz,
 unique(subscription_id,delivery_date,slot)
);
alter table public.arise_push_deliveries enable row level security;
revoke all on public.arise_push_deliveries from anon,authenticated;
grant all on public.arise_push_deliveries to service_role;
grant usage,select on sequence public.arise_push_deliveries_id_seq to service_role;
do $body$ begin
 if not exists(select 1 from vault.secrets where name='arise_scheduler_token') then
  perform vault.create_secret(encode(extensions.gen_random_bytes(32),'hex'),'arise_scheduler_token','ARISE scheduler authentication');
 end if;
end $body$;
create or replace function public.arise_scheduler_authorized(p_token text)
returns boolean language sql security definer set search_path=public,pg_temp as $body$
 select length(p_token)=64 and exists(select 1 from vault.decrypted_secrets where name='arise_scheduler_token'
 and extensions.digest(decrypted_secret,'sha256')=extensions.digest(p_token,'sha256'));
$body$;
create or replace function public.arise_claim_push()
returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $body$
declare local_now timestamp:=now() at time zone 'Asia/Yekaterinburg'; slot_name text; row record; delivery bigint; results jsonb:='[]';
begin
 if extract(hour from local_now) not in (9,21) then return results;end if;
 slot_name:=case when extract(hour from local_now)=9 then 'morning' else 'evening' end;
 for row in select s.* from public.push_subscriptions s join public.arise_accounts a on a.device_id=s.device_id
  where s.active and not exists(select 1 from public.arise_push_deliveries d where d.subscription_id=s.id and d.delivery_date=local_now::date and d.slot=slot_name)
  order by s.id limit 100 for update of s skip locked
 loop
  perform public.arise_daily_list(row.device_id,local_now::date,false);
  if not exists(select 1 from public.daily_instances where device_id=row.device_id and daily_date=local_now::date and status in ('active','rejected')) then continue;end if;
  insert into public.arise_push_deliveries(subscription_id,delivery_date,slot) values(row.id,local_now::date,slot_name)
   on conflict do nothing returning id into delivery;
  if not found then continue;end if;
  results:=results||jsonb_build_array(jsonb_build_object('delivery_id',delivery,'endpoint',row.endpoint,'p256dh',row.p256dh,'auth',row.auth,'slot',slot_name));
 end loop;
 return results;
end $body$;
create or replace function public.arise_finish_push(p_id bigint,p_status text)
returns void language plpgsql security invoker set search_path=public,pg_temp as $body$
declare sub bigint;
begin
 if p_status not in ('sent','failed','expired') then raise exception 'invalid_status';end if;
 update public.arise_push_deliveries set status=p_status,finished_at=now() where id=p_id and status='processing' returning subscription_id into sub;
 if found and p_status='expired' then update public.push_subscriptions set active=false,updated_at=now() where id=sub;end if;
end $body$;
create or replace function public.arise_dispatch_push(p_dry_run boolean default false)
returns bigint language sql security definer set search_path=public,pg_temp as $body$
 select net.http_post(url:='https://cnjmbzobtvfjqhedhwpj.supabase.co/functions/v1/arise-push',
 headers:=jsonb_build_object('Content-Type','application/json','x-arise-scheduler',(select decrypted_secret from vault.decrypted_secrets where name='arise_scheduler_token')),
 body:=jsonb_build_object('dry_run',p_dry_run),timeout_milliseconds:=120000);
$body$;
revoke all on function public.arise_scheduler_authorized(text),public.arise_claim_push(),public.arise_finish_push(bigint,text),public.arise_dispatch_push(boolean) from public,anon,authenticated;
grant execute on function public.arise_scheduler_authorized(text),public.arise_claim_push(),public.arise_finish_push(bigint,text) to service_role;
select cron.schedule('arise-daily-reminders','0 4,16 * * *','select public.arise_dispatch_push(false)');
commit;
