import test from 'node:test';import assert from 'node:assert/strict';
import {createHandler} from '../supabase/arise-functions/_shared/server.mjs';
import {evaluateFile} from '../supabase/arise-functions/_shared/evidence.mjs';
const user='a1111111-1111-4111-8111-111111111111',device='fixture-device-0123456789';
const env={get:k=>({SUPABASE_URL:'https://fixture.test',SUPABASE_SERVICE_ROLE_KEY:'fixture'})[k]};
function handler(action,fetcher){return createHandler(action,{env,now:()=>new Date('2026-10-03T12:00:00Z'),fetcher:async(input,init)=>{const url=new URL(input);if(url.pathname==='/auth/v1/user')return Response.json({id:user,email:'fixture@example.com',email_confirmed_at:'2026-10-01',is_anonymous:false});if(url.pathname.endsWith('/arise_account_device'))return Response.json(device);return fetcher(url,init);}});}
const req=(body,method='POST')=>new Request('https://fixture.test/action',{method,headers:{Authorization:'Bearer fixture','content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(body)}:{})});
test('physical daily challenge uses server-owned daily, never supplied quest/goal',async()=>{const response=await handler('physical-start',async(url,init)=>{if(url.pathname.endsWith('/daily_instances')){assert.equal(url.searchParams.get('device_id'),'eq.'+device);return Response.json([{id:1,physical_quest_index:58,verification_mode:'camera',status:'active'}]);}assert.ok(url.pathname.endsWith('/arise_physical_sessions'));if(init.method==='GET')return Response.json([]);const body=JSON.parse(init.body);assert.equal(body.quest_index,58);assert.equal(body.goal,10);assert.equal(body.daily_id,1);return Response.json([{id:'11111111-1111-4111-8111-111111111111',expires_at:'2026-10-03T12:15:00Z'}]);})(req({daily_id:1,quest_index:75,goal:0}));assert.equal(response.status,200);});
test('daily-sources scopes templates to the authenticated device',async()=>{const response=await handler('daily-sources',async(url)=>{assert.equal(url.searchParams.get('device_id'),'eq.'+device);assert.equal(url.searchParams.get('is_template'),'eq.true');return Response.json([]);})(req(null,'GET'));assert.equal(response.status,200);});
test('unassigned account cannot read review queue',async()=>{const response=await handler('review-queue',async url=>{assert.ok(url.pathname.endsWith('/arise_reviewers'));assert.equal(url.searchParams.get('user_id'),'eq.'+user);return Response.json([]);})(req(null,'GET'));assert.equal(response.status,403);});
test('audio proof is sent as audio, provider uncertainty gives no false completion',async()=>{let calls=0;const result=await evaluateFile(new File(['audio fixture'],'speech.mp3',{type:'audio/mpeg'}),{id:37,title:'Speech',mission:'Say the specified sentences'},{get:k=>k==='GEMINI_API_KEY'?'fixture':null},async(url,init)=>{calls++;const body=JSON.parse(init.body);assert.equal(body.contents[0].parts[1].inline_data.mime_type,'audio/mpeg');return Response.json({candidates:[{content:{parts:[{text:'{"decision":"uncertain","reason":"Недостаточно данных"}'}]}}]});});assert.equal(calls,1);assert.equal(result.check_status,'pending');});
