import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../supabase/arise-functions/_shared/server.mjs';
import {SKILLS} from '../arise/development-tree.mjs';
const user='a1111111-1111-4111-8111-111111111111',id='11111111-1111-4111-8111-111111111111',stamp='2026-10-03T12:00:00Z';
const env={get:k=>({SUPABASE_URL:'https://example.test',SUPABASE_SERVICE_ROLE_KEY:'fixture'})[k]};
function handler(fetcher){return createHandler('projects',{env,fetcher:async(input,init)=>{const url=new URL(input);if(url.pathname==='/auth/v1/user')return Response.json({id:user,email:'fixture@example.com',email_confirmed_at:stamp,is_anonymous:false});if(url.pathname.endsWith('/arise_account_device'))return Response.json('fixture-device-0123456789');return fetcher(url,init);}});}
function request(body){return new Request('https://example.test/projects',{method:'POST',headers:{Authorization:'Bearer fixture','content-type':'application/json'},body:JSON.stringify(body)});}
test('project edits cannot target another account',async()=>{let calls=0;const response=await handler(async(url,init)=>{calls++;assert.equal(init.method,'GET');assert.equal(url.searchParams.get('user_id'),'eq.'+user);assert.equal(url.searchParams.get('id'),'eq.'+id);return Response.json([]);})(request({action:'update',id,updated_at:stamp,title:'New project',skills:[]}));assert.equal(response.status,404);assert.equal(calls,1);});
test('stale project edits never write',async()=>{let calls=0;const response=await handler(async(url,init)=>{calls++;assert.equal(init.method,'GET');return Response.json([{id,title:'Robot',status:'active',updated_at:stamp}]);})(request({action:'update',id,updated_at:'2000-01-01T00:00:00Z',title:'Robot'}));assert.equal(response.status,409);assert.equal((await response.json()).error,'project_changed');assert.equal(calls,1);});
test('create saves project and skill links with one RPC',async()=>{let calls=0;const skill=SKILLS[0].id;const response=await handler(async(url,init)=>{calls++;assert.ok(url.pathname.endsWith('/rpc/arise_save_project'));const body=JSON.parse(init.body);assert.equal(body.p_user_id,user);assert.equal(body.p_id,null);assert.deepEqual(body.p_skills,[skill]);return Response.json({id,skills:[skill]});})(request({title:'Robot',skills:[skill,skill]}));assert.equal(response.status,201);assert.equal(calls,1);});
test('archive does not erase project skills and RPC rechecks concurrent updates',async()=>{const response=await handler(async(url,init)=>{if(init.method==='GET')return Response.json([{id,title:'Robot',description:'Result',status:'completed',updated_at:stamp}]);const body=JSON.parse(init.body);assert.equal(body.p_action,'archive');assert.equal(body.p_skills,null);assert.equal(body.p_expected_updated_at,stamp);return Response.json({error:'project_changed'});})(request({action:'archive',id,updated_at:stamp}));assert.equal(response.status,409);});
test('invalid skill identifiers and excess skills are rejected before any write',async()=>{for(const skills of [['made-up-skill'],SKILLS.slice(0,13).map(x=>x.id)]){const response=await handler(()=>{throw Error('must not write');})(request({title:'Robot',skills}));assert.equal(response.status,400);assert.equal((await response.json()).error,'invalid_project');}});
