import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../supabase/functions/fastgo-workshop-api/index.ts',import.meta.url),'utf8');
const uid='11111111-1111-4111-8111-111111111111',pid='22222222-2222-4222-8222-222222222222',rid='33333333-3333-4333-8333-333333333333';
const secret='dummy-test-secret-not-an-actual-secret';
function setup({role='owner',valid=true,active=true,connected=true,google,rawGoogle,googleResponse,contentResponse}={}){let handle;const calls=[];
const fetch=async(url,o={})=>{calls.push({url,o});if(url.startsWith('https://script.googleusercontent.com'))return contentResponse(url,o);if(url.endsWith('/auth/v1/user'))return Response.json(valid?{id:uid,email:'test@example.invalid'}:{},{status:valid?200:401});if(url.includes('/workshop_members'))return Response.json(active?[{profile_id:uid,role,active:true}]:[]);if(url.includes('/workshop_backend_config'))return Response.json([{sheets_api_url:'https://script.google.com/macros/s/TEST/exec',sheets_api_secret:connected?secret:''}]);if(url.startsWith('https://script.google.com')){if(o.method==='GET')return contentResponse(url,o);const b=JSON.parse(o.body);if(googleResponse)return googleResponse(b);if(rawGoogle)return Response.json(rawGoogle(b));return Response.json({data:google?google(b):b.action==='get'?{record:{id:rid,status:'accepted',revision:1,assigned_master_id:uid,works:[],parts:[],paid_amount:0,total_amount:0,fault_photo_paths:[],signed_document_paths:[]},events:[],payments:[]}:{parts:[{id:pid,name:'TEST',active:true,quantity:2,retail_price:100}],services:[],categories:[]}});}if(url.includes('/service_repairs?')||url.includes('/storage_intakes?'))return Response.json([]);throw new Error('unexpected '+url);};
vm.runInNewContext(source,{Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://auth.invalid':'dummy-server-key'},serve:fn=>handle=fn},Request,Response,Headers,URL,URLSearchParams,AbortSignal,Uint8Array,TextEncoder,TextDecoder,atob,fetch,crypto:globalThis.crypto});
return{calls,go:(body,auth=true,method='POST')=>handle(new Request('https://api.invalid/fastgo-workshop-api',{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer dummy-user-token'}:{})},body:method==='POST'?JSON.stringify(body):undefined}))};}
test('no auth means no data requests',async()=>{const s=setup();assert.equal((await s.go({action:'catalog'},false)).status,401);assert.equal(s.calls.length,0);});
test('invalid session and disabled member denied',async()=>{assert.equal((await setup({valid:false}).go({action:'catalog'})).status,401);assert.equal((await setup({active:false}).go({action:'catalog'})).status,403);});
test('unknown role cannot reach Google',async()=>{const s=setup({role:'customer'});assert.equal((await s.go({action:'catalog'})).status,403);assert.ok(!s.calls.some(x=>x.url.includes('script.google')));});
test('OPTIONS contains CORS without data',async()=>{const s=setup();const r=await s.go({},false,'OPTIONS');assert.equal(r.status,204);assert.equal(s.calls.length,0);});
test('health and me disclose backend not secret',async()=>{const s=setup();for(const r of [await s.go({},false,'GET'),await s.go({action:'me'})]){assert.equal(r.status,200);assert.match(await r.text(),/GOOGLE_SHEETS_DRIVE/);}});
test('catalog uses Google and verified actor; credentials not exposed',async()=>{const s=setup();const r=await s.go({action:'catalog',actor:{role:'owner',id:'forged'}});assert.equal(r.status,200);const txt=await r.text();assert.ok(!txt.includes(secret));assert.ok(!s.calls.some(c=>c.url.includes('/rest/v1/parts')));const b=JSON.parse(s.calls.find(c=>c.url.includes('script.google')).o.body);assert.equal(b.actor.id,uid);assert.equal(b.secret,secret);});
test('missing Google config fails closed; no fallback',async()=>{const s=setup({connected:false});assert.equal((await s.go({action:'catalog'})).status,503);assert.ok(!s.calls.some(c=>c.url.includes('/parts')));});
test('negative and fractional stock inputs rejected',async()=>{for(const quantity of [-1,0,1.5]){const s=setup();const r=await s.go({action:'stock',params:{part_id:pid,request_id:rid,note:'test',movement_type:'receipt',quantity}});assert.equal(r.status,400);assert.ok(!s.calls.some(c=>c.url.includes('script.google')));}});
test('sale aggregates duplicate products and takes server price',async()=>{let sent;const s=setup({google:b=>{if(b.action==='catalog')return{parts:[{id:pid,active:true,retail_price:100,quantity:10}]};sent=b;return{sale_number:1};}});assert.equal((await s.go({action:'sale',params:{request_id:rid,payment_method:'cash',items:[{part_id:pid,quantity:1,price:-100},{part_id:pid,quantity:2,price:1}]}})).status,200);assert.deepEqual(sent.params.items,[{part_id:pid,quantity:3,price:100}]);});
test('mechanic forbidden money mutations',async()=>{for(const action of ['payment','stock','sale','finance','customers'])assert.equal((await setup({role:'mechanic'}).go({action,params:{}})).status,403);});
test('non-admin cannot refund',async()=>{const r=await setup({role:'manager'}).go({action:'payment',params:{id:rid,request_id:pid,amount:-1,method:'cash',note:'refund'}});assert.equal(r.status,403);});
test('stale revision fails before mutation',async()=>{const r=await setup().go({action:'update',params:{id:rid,revision:99,status:'repair'}});assert.equal(r.status,409);});
test('cannot attach arbitrary private Drive file',async()=>{const r=await setup().go({action:'documents',params:{id:rid,slot:'photos',paths:['https://drive.google.com/file/d/unknown/view']}});assert.equal(r.status,403);});
test('cannot issue an unpaid/unapproved repair',async()=>{const r=await setup().go({action:'update',params:{id:rid,revision:1,status:'issued'}});assert.equal(r.status,409);});
test('formula-like user text neutralized before Sheets write',async()=>{let received;const s=setup({google:b=>{received=b;return{movement_id:'m'};}});const r=await s.go({action:'stock',params:{part_id:pid,request_id:rid,quantity:1,movement_type:'receipt',note:'=IMPORTXML("evil")'}});assert.equal(r.status,200);assert.ok(received.params.note.startsWith("'="));});

test('atomic backend resolves committed retry before stale revision validation',async()=>{const s=setup({google:b=>b.action==='health'?{capabilities:{atomic_writes:true}}:b.action==='operation_retry'?{status:'committed',result:{id:rid,revision:3}}:null});const r=await s.go({action:'update',params:{request_id:pid,id:rid,revision:1,status:'repair'}});assert.equal(r.status,200);assert.equal((await r.json()).data.revision,3);assert.ok(!s.calls.some(x=>x.url.includes('script.google')&&JSON.parse(x.o.body).action==='get'));});
test('private product upload is gated while old Google backend is installed',async()=>{const r=await setup().go({action:'part_photo_upload',params:{request_id:rid,part_id:pid,content_type:'image/png',content_base64:'dGVzdA=='}});assert.equal(r.status,503);});

test('doGet availability response cannot masquerade as successful data or write',async()=>{for(const action of ['catalog','stock']){const s=setup({rawGoogle:()=>({ok:true,service:'FastGo Google Sheets API'})});const r=await s.go({action,params:{part_id:pid,request_id:rid,quantity:1,movement_type:'receipt',note:'test'}});assert.equal(r.status,502);assert.ok(!(await r.text()).includes(secret));}});
test('null or missing upstream result fails closed',async()=>{for(const value of [{},{data:null}])assert.equal((await setup({rawGoogle:()=>value}).go({action:'catalog'})).status,502);});
test('malformed catalogue is rejected with 502',async()=>{assert.equal((await setup({google:()=>({parts:[],services:[]})}).go({action:'catalog'})).status,502);});
test('public health declares upstream is not checked',async()=>{assert.equal((await (await setup().go({},false,'GET')).json()).upstream_checked,false);});
test('contact phone checked at server boundary',async()=>{assert.equal((await setup().go({action:'contact',params:{id:rid,revision:1,phone:'123'}})).status,400);});

test('non-JSON Google responses expose only fixed diagnostic codes',async()=>{const s=setup({googleResponse:()=>new Response('<html><title>Moved Temporarily</title>'+secret+'<a href="https://example.invalid/?token=private-token">private client</a></html>',{headers:{'Content-Type':'text/html'}})});const r=await s.go({action:'catalog'});assert.equal(r.status,502);const message=(await r.json()).error;assert.match(message,/script\/redirect\/200/);assert.ok(!message.includes(secret));assert.ok(!message.includes('private-token'));assert.ok(!message.includes('private client'));});

test('ContentService redirect uses credential-free GET and disallows foreign targets',async()=>{
  const s=setup({googleResponse:()=>new Response(null,{status:302,headers:{location:'https://script.googleusercontent.com/macros/echo?user_content_key=one-time'}}),contentResponse:(url,o)=>{assert.equal(o.method,'GET');assert.equal(o.body,undefined);assert.equal(o.headers.Authorization,undefined);assert.equal(o.headers['Content-Type'],undefined);return Response.json({data:{parts:[],categories:[],services:[],capabilities:{}}});}});
  assert.equal((await s.go({action:'catalog'})).status,200);
  for(const target of ['https://evil.invalid/','https://script.googleusercontent.com.evil.invalid/','http://script.googleusercontent.com/','https://user:pass@script.googleusercontent.com/']){
    const denied=setup({googleResponse:()=>new Response(null,{status:302,headers:{location:target}})});
    assert.equal((await denied.go({action:'catalog'})).status,502);assert.ok(!denied.calls.some(c=>c.url===target));
  }
});
test('transient lost Google response retries reads but never business writes',async()=>{
  let reads=0;const s=setup({googleResponse:()=>++reads===1?new Response('<html>Page Not Found</html>',{status:404}):Response.json({data:{parts:[],categories:[],services:[],capabilities:{}}})});assert.equal((await s.go({action:'catalog'})).status,200);assert.equal(reads,3);const urls=s.calls.filter(c=>c.url.startsWith('https://script.google.com')).map(c=>c.url);assert.equal(new Set(urls).size,urls.length);
  let writes=0;const w=setup({googleResponse:b=>b.action==='health'?Response.json({data:{capabilities:{}}}):(++writes,new Response('<html>Page Not Found</html>',{status:404}))});assert.equal((await w.go({action:'stock',params:{part_id:pid,request_id:rid,quantity:1,movement_type:'receipt',note:'test'}})).status,502);assert.equal(writes,1);
});

test('ContentService can redirect a response again without forwarding credentials',async()=>{let hops=0;const s=setup({googleResponse:()=>new Response(null,{status:302,headers:{location:'https://script.googleusercontent.com/macros/echo?response=one'}}),contentResponse:(url,o)=>{assert.equal(o.method,'GET');assert.equal(o.body,undefined);if(++hops%2)return new Response(null,{status:307,headers:{location:'https://script.googleusercontent.com/macros/echo?response=two'}});return Response.json({data:{parts:[],categories:[],services:[],capabilities:{}}});}});assert.equal((await s.go({action:'catalog'})).status,200);assert.equal(hops,4);});

test('redirect response cleanup cannot delay retrieving the Google result',async()=>{const s=setup({googleResponse:()=>new Response(new ReadableStream({cancel:()=>new Promise(()=>{})}),{status:302,headers:{location:'https://script.googleusercontent.com/macros/echo?result=cleanup-test'}}),contentResponse:()=>Response.json({data:{parts:[],categories:[],services:[],capabilities:{}}})});const result=await Promise.race([s.go({action:'catalog'}),new Promise((_,reject)=>setTimeout(()=>reject(Error('redirect cleanup blocked response')),500))]);assert.equal(result.status,200);});

test('Google response may return to this deployment by GET, never to another deployment',async()=>{for(const safe of [true,false]){let hop=0;const s=setup({googleResponse:()=>new Response(null,{status:302,headers:{location:'https://script.googleusercontent.com/macros/echo?result=return'}}),contentResponse:(url,o)=>{assert.equal(o.method,'GET');assert.equal(o.body,undefined);if(url.startsWith('https://script.googleusercontent.com'))return new Response(null,{status:302,headers:{location:'https://script.google.com/macros/s/'+(safe?'TEST':'OTHER')+'/exec?response=return'}});hop++;return Response.json({data:{parts:[],categories:[],services:[],capabilities:{}}});}});assert.equal((await s.go({action:'catalog'})).status,safe?200:502);assert.equal(hop,safe?2:0);}});

test('catalogue reuses capabilities only, never business data or write health checks',async()=>{
 const s=setup({google:b=>b.action==='health'?{capabilities:{private_product_photos:true}}:{parts:[],services:[],categories:[]}});
 for(let i=0;i<2;i++)assert.equal((await s.go({action:'catalog'})).status,200);
 const actions=()=>s.calls.filter(c=>c.url.startsWith('https://script.google.com')).map(c=>JSON.parse(c.o.body).action);
 assert.equal(actions().filter(x=>x==='health').length,1);assert.equal(actions().filter(x=>x==='catalog').length,2);
 await s.go({action:'stock',params:{part_id:pid,request_id:rid,quantity:1,movement_type:'receipt',note:'test'}});
 assert.equal(actions().filter(x=>x==='health').length,2);
});
