import test from 'node:test';
import assert from 'node:assert/strict';
import {numberCell,planImport,receiptId,checkpointStore,runImport,digestBytes} from '../workshop/inventory-import-core.js';
const product={id:'11111111-1111-4111-8111-111111111111',name:'Подшипник',category:'bearing',model:'2008 2RS',sku:'B-2',barcode:'FGP-00000001',unit:'шт',unit_cost:85,retail_price:250,active:true};
const catalog={parts:[product],categories:[{name:'bearing',label:'Подшипники'}]};
const row={'Модель / название':'Подшипник','Категория':'Подшипники','Модель':'2008 2RS','Штрих-код':product.barcode,'Приход, шт.':2};
const storage=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
test('blank prices preserve existing prices and category key',()=>{const [r]=planImport([row],catalog);assert.equal(r.product.retail_price,250);assert.equal(r.product.unit_cost,85);assert.equal(r.product.category,'bearing');assert.equal(r.quantity,2);});
test('explicit zero remains explicit, disabled items are not reactivated',()=>{const [r]=planImport([{...row,'Цена продажи, ₽':0}],{...catalog,parts:[{...product,active:false}]});assert.equal(r.product.retail_price,0);assert.equal(r.product.active,false);});
test('localized decimal amounts accepted',()=>{assert.equal(numberCell('1 250,50','Цена'),1250.5);assert.equal(numberCell('2\u202f500','Количество',{integer:true}),2500);});
test('negative, malformed and fractional quantities fail, not rounded',()=>{for(const q of ['-1','1.5','abc','2 шт',Infinity,true])assert.throws(()=>planImport([{...row,'Приход, шт.':q}],catalog),/Импорт не начат/);});
test('conflicting barcode and SKU rejected before any writes',()=>{assert.throws(()=>planImport([{...row,SKU:'OTHER'}],{...catalog,parts:[product,{...product,id:'other',sku:'OTHER',barcode:'FGP-00000002',name:'Другой'}]}),/разные товары/);});
test('duplicate file rows and ambiguous database IDs rejected',()=>{assert.throws(()=>planImport([row,row],catalog),/повторяется/);assert.throws(()=>planImport([row],{...catalog,parts:[product,{...product,id:'another'}]}),/несколько товаров/);});
test('new category and AUTO code allowed, unknown supplied barcode rejected',()=>{const r={'Название':'Новое','Категория':'Новая','Штрих-код':'AUTO'};assert.equal(planImport([r],catalog)[0].product.name,'Новое');assert.throws(()=>planImport([{...r,'Штрих-код':'FGP-9999'}],catalog),/Неизвестный/);});
test('one invalid row rejects the whole plan',()=>{assert.throws(()=>planImport([row,{'Название':'Новый','Категория':'X','Количество':-2}],catalog),/Строка 3/);});
test('receipt UUID stable for same file and row, distinct for different delivery',async()=>{const a=await receiptId('a'.repeat(64),2,product.id);assert.equal(a,await receiptId('a'.repeat(64),2,product.id));assert.notEqual(a,await receiptId('b'.repeat(64),2,product.id));assert.match(a,/^[a-f0-9]{8}-[a-f0-9]{4}-8[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);});
test('completed file cannot apply stock twice',async()=>{const checkpoint=checkpointStore(storage(),'hash'),calls=[],plan=planImport([row],catalog);const api=async(a,p)=>{calls.push([a,p]);return {id:'receipt'};};await runImport(plan,{api,catalog,fileHash:'hash',checkpoint});assert.equal((await runImport(plan,{api,catalog,fileHash:'hash',checkpoint})).alreadyDone,true);assert.equal(calls.filter(x=>x[0]==='stock').length,1);});
test('unknown result stops subsequent rows, resume reuses receipt UUID',async()=>{const st=storage(),checkpoint=checkpointStore(st,'hash'),calls=[];const second={...product,id:'22222222-2222-4222-8222-222222222222',name:'Другой',sku:'OTHER',barcode:'FGP-00000002'};const c={...catalog,parts:[product,second]},plan=planImport([row,{...row,'Модель / название':'Другой','Штрих-код':second.barcode}],c);let broken=true;
 const api=async(a,p)=>{calls.push([a,p]);if(broken){broken=false;throw new Error('network');}return {id:'receipt'};};
 await assert.rejects(()=>runImport(plan,{api,catalog:c,fileHash:'hash',checkpoint}),/network/);assert.equal(calls.length,1);const original=calls[0][1].request_id;
 await runImport(plan,{api,catalog:c,fileHash:'hash',checkpoint:checkpointStore(st,'hash')});assert.equal(calls[1][1].request_id,original);assert.equal(calls.length,3);
});
test('storage failure stops before network writes',()=>{assert.throws(()=>checkpointStore({getItem:()=>null,setItem:()=>{throw new Error('quota');}},'x'),/quota/);});
test('SHA256 hashes bytes not file name',async()=>{const data=new TextEncoder().encode('same workbook');assert.equal(await digestBytes(data),await digestBytes(data));});
