import test from 'node:test';
import assert from 'node:assert/strict';
import {loadProductIntake,startProductIntake,continueProductIntake} from '../workshop/product-intake.js';
const product={name:'QA',category:'Test',model:'Model',sku:'QA-1',unit_cost:0,retail_price:0,unit:'шт'};
const spec={product,quantity:1,photo:{sha256:'image-hash',type:'image/png',primary:true}};
function storage(){const data=new Map();return {data,getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
function server(lost){const receipts=new Map(),counts={part:0,stock:0,photo:0},ids=[];let lose=lost;const commit=(step,id)=>{ids.push([step,id]);if(receipts.has(id))return receipts.get(id);counts[step]++;const result={id:'product-id',barcode:'FGP-00000081'};receipts.set(id,result);if(lose===step){lose=null;throw Error('response lost');}return result;};return {counts,ids,api:async(a,p)=>commit(a==='part_save'?'part':'stock',p.request_id),uploadPhoto:async(p,m,id)=>commit('photo',id)};}
for(const step of ['part','stock','photo'])test(`reload after lost ${step} response resumes once with original IDs`,async()=>{const s=storage(),backend=server(step);const original=startProductIntake(s,'owner',spec);await assert.rejects(()=>continueProductIntake(s,'owner',backend),/response lost/);assert.ok(loadProductIntake(s,'owner'));const resumed=startProductIntake(s,'owner',{...spec,quantity:90,product:{...product,name:'Changed'}});assert.equal(resumed.quantity,1);assert.equal(resumed.product.name,'QA');assert.deepEqual(resumed.ids,original.ids);await continueProductIntake(s,'owner',backend);assert.deepEqual(backend.counts,{part:1,stock:1,photo:1});assert.equal(loadProductIntake(s,'owner'),null);assert.equal(backend.ids.filter(x=>x[0]===step).length,2);});
test('storage write failure after committed receipt retains original replay ID',async()=>{const s=storage(),backend=server();startProductIntake(s,'owner',spec);const save=s.setItem;s.setItem=(k,v)=>{if(JSON.parse(v).received)throw Error('quota');save(k,v);};await assert.rejects(()=>continueProductIntake(s,'owner',backend),/quota/);s.setItem=save;await continueProductIntake(s,'owner',backend);assert.deepEqual(backend.counts,{part:1,stock:1,photo:1});});
test('storage unavailable stops before any product submission',()=>{const s=storage();s.setItem=()=>{throw Error('quota');};assert.throws(()=>startProductIntake(s,'owner',spec),/quota/);assert.equal(loadProductIntake(s,'owner'),null);});
test('pending intake belongs to its employee and does not store image bytes',()=>{const s=storage();startProductIntake(s,'owner',spec);assert.equal(loadProductIntake(s,'receiver'),null);assert.equal(JSON.stringify([...s.data]).includes('content_base64'),false);});
test('known initial rejection allows correcting product without retaining a stuck checkpoint',async()=>{const s=storage();startProductIntake(s,'owner',spec);await assert.rejects(()=>continueProductIntake(s,'owner',{api:async()=>{throw Object.assign(Error('duplicate SKU'),{status:409});}}),/duplicate SKU/);assert.equal(loadProductIntake(s,'owner'),null);});
test('finished checkpoint left by failed cleanup does not add stock or upload again',async()=>{const s=storage(),backend=server();startProductIntake(s,'owner',spec);const remove=s.removeItem;s.removeItem=()=>{throw Error('cleanup failed');};await assert.rejects(()=>continueProductIntake(s,'owner',backend),/cleanup failed/);s.removeItem=remove;await continueProductIntake(s,'owner',backend);assert.deepEqual(backend.counts,{part:1,stock:1,photo:1});});
test('corrupt checkpoint cannot silently create a new operation',()=>{const s=storage();s.setItem('fastgo_product_intake_v1:owner','broken');assert.throws(()=>startProductIntake(s,'owner',spec),/сверьте склад/);});
