import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../supabase/functions/fastgo-workshop-api/index.ts',import.meta.url),'utf8');
const user='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
function setup({role='owner',active=true,valid=true,record={},respond}={}){let handler;const calls=[];const fetch=async(url,options={})=>{calls.push({url,options});if(url.endsWith('/auth/v1/user'))return Response.json(valid?{id:user}:{error:'invalid'},{status:valid?200:401});if(url.includes('/workshop_members'))return Response.json(active?[{profile_id:user,name:'QA',role,active:true}]:[]);if(url.includes('/service_repairs?'))return Response.json([{id,assigned_master_id:user,fault_photo_paths:[],signed_document_paths:[],...record}]);if(respond)return respond(url,options);throw new Error('Unexpected fetch: '+url);};const context={Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://db.invalid':'test-server-key'},serve:fn=>handler=fn},Request,Response,Headers,URL,URLSearchParams,AbortSignal,Uint8Array,atob,fetch,crypto:globalThis.crypto};vm.runInNewContext(source,context);return {calls,invoke:(body,headers={Authorization:'Bearer test-user-jwt'},method='POST')=>handler(new Request('https://edge.invalid/fastgo-workshop-api',{method,headers:{'Content-Type':'application/json',...headers},body:method==='POST'?JSON.stringify(body):undefined}))};}
test('unauthenticated caller cannot query data',async()=>{const s=setup();assert.equal((await s.invoke({action:'list'},{})).status,401);assert.equal(s.calls.length,0);});
test('invalid JWT cannot query records',async()=>{const s=setup({valid:false});assert.equal((await s.invoke({action:'get',params:{id}})).status,401);assert.equal(s.calls.length,1);});
test('inactive membership is enforced independently of token',async()=>{const s=setup({active:false});assert.equal((await s.invoke({action:'list'})).status,403);assert.equal(s.calls.length,2);});
test('CORS supports authenticated JSON requests',async()=>{const s=setup();const r=await s.invoke(null,{},'OPTIONS');assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Headers'),/authorization/);assert.equal(s.calls.length,0);});
test('mechanic cannot open storage',async()=>{const s=setup({role:'mechanic'});assert.equal((await s.invoke({action:'list',params:{kind:'storage'}})).status,403);});
test('mechanic cannot open another mechanics repair',async()=>{const s=setup({role:'mechanic',record:{assigned_master_id:'other'}});assert.equal((await s.invoke({action:'get',params:{kind:'repair',id}})).status,403);});
test('a record cannot sign an unrelated document',async()=>{const s=setup();const r=await s.invoke({action:'signed_url',params:{id,kind:'repair',path:'rental/other-client.pdf'}});assert.equal(r.status,403);assert.equal(s.calls.filter(c=>c.url.includes('/storage/v1/')).length,0);});
test('mutation actor comes from verified identity',async()=>{const s=setup({respond:async(url,options)=>{assert.match(url,/rpc\/workshop_mutate/);const body=JSON.parse(options.body);assert.equal(body.p_actor,user);return Response.json({id});}});const r=await s.invoke({action:'payment',params:{kind:'repair',id,p_actor:'forged-id'}});assert.equal(r.status,200);});
test('database conflicts are reported as conflicts',async()=>{const s=setup({respond:async()=>Response.json({code:'40001',message:'Card was updated'},{status:400})});const r=await s.invoke({action:'update',params:{id}});assert.equal(r.status,409,await r.text());});
test('non-admin cannot change staff',async()=>{const s=setup({role:'receiver'});const r=await s.invoke({action:'staff_create',params:{}});assert.equal(r.status,403,await r.text());});
