import {icon} from './icons.js';
import {orderBoard} from './board.js';
import {api,invalidateReads,esc,money,date,today,fio,number,roles,statuses,badge,opts,sessionAvailable,signIn,signUp,signOut,csvDownload} from './core.js';
import {renderIntake,renderDetail} from './orders.js';
import {renderDocument} from './documents.js';
const $=id=>document.getElementById(id),app=$('app');let me=null,epoch=0,cache=null,dirty=false,loadingTimer=null;
const nav=[['home','Главная','◈'],['repairs','Ремонты','⚒'],['storage','Хранение','▣'],['clients','Клиенты','♙'],['stock','Склад','▤'],['finance','Оплаты','₽'],['catalog','Прайс работ','≡'],['staff','Сотрудники','♧'],['account','Аккаунт','●'],['settings','Реквизиты','⚙']];
const admin=()=>['owner','admin'].includes(me?.role),manager=()=>me?.role!=='mechanic';
let currentPage='home';
function visibleNav(){return nav.filter(([n])=>manager()||['home','repairs','stock','catalog','account'].includes(n)).filter(([n])=>admin()||n!=='staff').filter(([n])=>me.role==='owner'||n!=='settings');}
function route(){let [page,qs]=(location.hash.slice(1)||'home').split('?');return{page,p:Object.fromEntries(new URLSearchParams(qs||''))};}
function href(page,p={}){const q=new URLSearchParams(Object.entries(p).filter(([,v])=>v!==undefined&&v!==null&&v!==''));return '#'+page+(q.size?'?'+q:'');}
function go(page,p={}){const hash=href(page,p);if(location.hash===hash)render();else location.hash=hash;}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3500);}
function mount(html,token=epoch){if(token!==epoch)return false;clearTimeout(loadingTimer);const vn=visibleNav(),mobile=vn.filter(([id])=>['home','repairs','storage','stock'].includes(id));app.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#home">Fast<span>Go</span><small>СЕРВИС ЭЛЕКТРОТРАНСПОРТА</small></a><nav class="nav" aria-label="Главное меню">${vn.map(([id,name,mark])=>`<a href="#${id}" class="${currentPage===id?'active':''}"><span class="nav-mark" aria-hidden="true">${icon(id)}</span>${name}</a>`).join('')}</nav><div class="sidebar-note"><span>СЕРВИС С ХАРАКТЕРОМ</span><p>Движение должно<br>продолжаться.</p></div><div class="profile"><b>${esc(me.name||me.email)}</b><div class="muted">${esc(roles[me.role])}</div><button class="btn ghost small" data-logout>Выйти</button></div></aside><div class="content"><main class="workspace" id="workspace">${html}</main></div></div><nav class="mobile-nav" aria-label="Разделы" style="--nav-count:${mobile.length+1}">${mobile.map(([id,name,mark])=>`<a href="#${id}" class="${currentPage===id?'active':''}"><span aria-hidden="true">${icon(id)}</span>${name}</a>`).join('')}<button id="more-nav"><span aria-hidden="true">${icon('more')}</span>Ещё</button></nav>`;
 document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=logout);$('more-nav').onclick=()=>modal('Разделы',`<nav class="nav" style="margin-top:0">${vn.filter(([id])=>!mobile.some(([m])=>m===id)).map(([id,n,mark])=>`<a href="#${id}" data-close><span>${icon(id)}</span>${n}</a>`).join('')}</nav><p class="muted">${esc(me.name||me.email)} · ${esc(roles[me.role])}</p><button type="button" class="btn ghost" id="logout-mobile">Выйти</button>`,null,()=>{$('logout-mobile').onclick=logout;document.querySelectorAll('[data-close]').forEach(a=>a.onclick=()=> $('dialog').close());});return true;
}
function modal(title,html,onSubmit,onOpen){const d=$('dialog');d.innerHTML=`<form id="modal-form"><div class="dialoghead"><h2>${esc(title)}</h2><button class="btn ghost small" type="button" data-close aria-label="Закрыть">✕</button></div>${html}<div id="modal-error" role="alert"></div>${onSubmit?'<div class="dialogfoot"><button class="btn secondary" type="button" data-close>Отмена</button><button class="btn" type="submit">Сохранить</button></div>':''}</form>`;d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());if(!d.open)d.showModal();d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(!onSubmit)return;const b=e.submitter;b.disabled=true;try{await onSubmit(Object.fromEntries(new FormData(e.target)),e.target);d.close();}catch(e){$('modal-error').innerHTML=`<p class="error">${esc(e.message)}</p>`;}finally{b.disabled=false;}};onOpen?.();}
async function run(button,fn){if(button?.disabled)return;button&&(button.disabled=true);try{await fn();}catch(e){modal('Не удалось выполнить действие',`<p class="error">${esc(e.message)}</p>`);}finally{button&&(button.disabled=false);}}
async function catalog(force=false){return api('catalog',{}, {fresh:force});}
const empty=(text,action='')=>`<div class="empty"><strong>${esc(text)}</strong>${action}</div>`;
const head=(title,sub='',action='')=>`<div class="pagehead"><div><h1>${title}</h1>${sub?`<p class="muted">${sub}</p>`:''}</div>${action}</div>`;
const field=(name,label,value='',type='text',required=false)=>`<div class="field"><label for="f-${name}">${label}${required?' *':''}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}"${required?' required':''}></div>`;
function pagination(count,offset=0,size=50){return `<div class="pagination"><span>${count?`${Number(offset)+1}–${Math.min(Number(offset)+size,count)} из ${count}`:'0 записей'}</span><div class="actions"><button class="btn ghost small" id="prev" ${Number(offset)<=0?'disabled':''}>Назад</button><button class="btn ghost small" id="next" ${Number(offset)+size>=count?'disabled':''}>Далее</button></div></div>`;}
function bindPagination(page,p,count,size=50){if($('prev'))$('prev').onclick=()=>go(page,{...p,offset:Math.max(0,Number(p.offset||0)-size)});if($('next'))$('next').onclick=()=>go(page,{...p,offset:Number(p.offset||0)+size});}
function rows(items,k){return items.map(r=>{const due=k==='repair'?r.promised_date:r.planned_return_date,late=due&&due<today()&&!['ready','issued','returned','cancelled'].includes(r.status);return `<tr><td data-label="Заказ"><a class="order-no" href="${href('order',{kind:k,id:r.id})}">${k==='repair'?'Р':'Х'}-${number(r,k)}</a><small>${date(r.created_at)}</small></td><td data-label="Техника"><b>${esc(r.brand)} ${esc(r.model)}</b><small>${esc(r.serial_number||'Без серийного номера')}</small></td><td data-label="Клиент">${esc(fio(r))}<small><a href="tel:${esc(r.phone)}">${esc(r.phone)}</a></small></td><td data-label="Статус">${badge(r.status,k)}<small>${esc(k==='repair'?r.assigned_master||'Мастер не назначен':r.storage_location||'Место не указано')}</small></td><td data-label="${k==='repair'?'Готовность':'До выдачи'}" class="${late?'late':''}">${date(due)}${late?'<small class="late">Срок прошёл</small>':''}</td><td data-label="Стоимость"><span class="amount">${money(k==='repair'?r.total_amount:r.storage_amount)}</span><small class="${Number((k==='repair'?r.total_amount:r.storage_amount)||0)-Number(r.paid_amount)>0?'debt':''}">${Number((k==='repair'?r.total_amount:r.storage_amount)||0)-Number(r.paid_amount)>0?'Осталось '+money(Number((k==='repair'?r.total_amount:r.storage_amount)||0)-Number(r.paid_amount)):'Оплачено'}</small></td><td><a class="btn ghost small" href="${href('order',{kind:k,id:r.id})}">Открыть</a></td></tr>`;}).join('');}
function table(items,k){return items.length?`<div class="panel flush"><table class="records"><thead><tr><th>Заказ</th><th>Техника</th><th>Клиент</th><th>Статус / ${k==='repair'?'мастер':'место'}</th><th>${k==='repair'?'Готовность':'Выдача'}</th><th>Стоимость</th><th></th></tr></thead><tbody>${rows(items,k)}</tbody></table></div>`:empty('Приёмок пока нет',manager()?`<a class="btn" href="${href('new',{kind:k})}">+ Новая приёмка</a>`:'');}
function login(error='',register=false,email=''){
 me=null;clearTimeout(loadingTimer);
 app.innerHTML=`<main class="login-shell"><section class="login-intro"><small>FASTGO / КОМАНДА СЕРВИСА</small><h2>Сервис<br>с характером<span>.</span></h2><p>Ремонт электротранспорта, зимнее хранение и склад в одном рабочем пространстве.</p></section><form class="login-card" id="login"><div class="brand">Fast<span>Go</span><small>СЕРВИС ЭЛЕКТРОТРАНСПОРТА</small></div><h1>${register?'Регистрация сотрудника':'Вход для сотрудников'}</h1>${register?field('name','Имя и фамилия','','text',true):''}${field('email','Электронная почта',email,'email',true)}<div class="field"><label for="password">Пароль${register?' (от 12 символов)':''}</label><div class="password-wrap"><input id="password" name="password" type="password" autocomplete="${register?'new-password':'current-password'}" ${register?'minlength="12"':''} required><button type="button" id="show-password">Показать</button></div></div>${register?field('confirm','Повторите пароль','','password',true):''}<div id="login-error" role="alert">${error?`<p class="error">${esc(error)}</p>`:''}</div><button class="btn" type="submit">${register?'Зарегистрироваться':'Войти'}</button><button class="btn secondary" type="button" id="auth-switch">${register?'Уже есть аккаунт — войти':'Создать аккаунт'}</button><footer>${register?'После регистрации вы сразу войдёте в приложение. Руководитель назначит вам роль и откроет доступ к заказам.':'Используйте почту и пароль своей учётной записи FastGo.'}</footer></form></main>`;
 $('f-email').autocomplete='username';
 if(register){$('f-name').autocomplete='name';$('f-confirm').autocomplete='new-password';}
 $('auth-switch').onclick=()=>login('',!register,$('f-email').value);
 $('show-password').onclick=()=>{const p=$('password');p.type=p.type==='password'?'text':'password';if(register)$('f-confirm').type=p.type;$('show-password').textContent=p.type==='password'?'Показать':'Скрыть';};
 $('login').onsubmit=async e=>{
  e.preventDefault();const b=e.submitter;b.disabled=true;$('auth-switch').disabled=true;$('login-error').textContent='';
  try{
   if(register){
    if($('password').value!==$('f-confirm').value)throw new Error('Пароли не совпадают');
    await signUp($('f-name').value,$('f-email').value.trim(),$('password').value);
   }else await signIn($('f-email').value.trim(),$('password').value);
   await enterWorkshop();
  }catch(e){if($('login-error'))$('login-error').innerHTML=`<p class="error">${esc(e.message)}</p>`;}
  finally{b.disabled=false;if($('auth-switch'))$('auth-switch').disabled=false;}
 };
}
async function enterWorkshop(){
 const access=await api('request_access',{}, {fresh:true});
 if(!access.active){pendingAccess(access);return;}
 me=await api('me');await render();
}
function pendingAccess(access={},error=''){
 me=null;clearTimeout(loadingTimer);
 const disabled=access.state==='disabled',requested=access.requested_at?date(access.requested_at):'';
 app.innerHTML=`<main class="login-shell"><section class="login-card"><div class="brand">Fast<span>Go</span></div><h1>${disabled?'Доступ отключён':'Заявка отправлена'}</h1><p>${disabled?'Руководитель отключил доступ к рабочему пространству FastGo. Обратитесь к владельцу или администратору.':'Аккаунт создан. Заявка на доступ уже находится у руководителя. По умолчанию новый сотрудник запрашивает роль «Мастер».'}</p>${!disabled&&requested?`<p class="muted">Заявка от ${esc(requested)}</p>`:''}<p>${disabled?'После повторного включения доступа нажмите кнопку ниже.':'После одобрения роли нажмите «Проверить доступ» — повторно регистрироваться не нужно.'}</p><div id="access-error" role="alert">${error?`<p class="error">${esc(error)}</p>`:''}</div><button class="btn" id="check-access">Проверить доступ</button><button class="btn secondary" id="access-logout">Выйти</button></section></main>`;
 $('check-access').onclick=async e=>{e.target.disabled=true;try{await enterWorkshop();}catch(err){pendingAccess(access,err.message);}};
 $('access-logout').onclick=logout;
}
async function logout(){if(dirty&&!confirm('Есть несохранённые изменения. Выйти?'))return;dirty=false;$('dialog').close();cache=null;await signOut();epoch++;login();}
async function home(token){
 if(!mount(head('Заявки и хранение', 'Ремонт. Хранение. Всё под контролем.',manager()?`<div class="home-actions"><a class="btn" href="#new?kind=repair">${icon('repairs')} Принять в ремонт</a><a class="btn secondary storage-action" href="#new?kind=storage">${icon('storage')} Зимнее хранение</a><div id="home-sale-slot"></div></div>`:'')+`<section id="home-stats" aria-live="polite"><div class="panel muted">Загружаем сводку…</div></section><div class="panelhead"><h2>Последние активные ремонты</h2><a class="btn ghost small" href="#repairs">Все ремонты</a></div><section id="home-orders" aria-live="polite"><div class="panel muted">Загружаем ремонты…</div></section>`,token))return;
 const fill=async(id,load,view)=>{
  const host=$(id);if(!host||token!==epoch)return;
  host.innerHTML='<div class="panel muted">Загружаем данные…</div>';
  const timer=setTimeout(()=>{if(token===epoch&&host.isConnected)host.innerHTML='<div class="panel muted">База отвечает дольше обычного. Можно перейти к приёмке или в другой раздел.</div>';},12000);
  try{const data=await load();if(token===epoch&&host.isConnected)host.innerHTML=view(data);}
  catch(e){if(token!==epoch||!host.isConnected)return;host.innerHTML=`<div class="error" role="alert">${esc(e.message)}</div><button class="btn secondary" type="button">Повторить загрузку</button>`;host.querySelector('button').onclick=()=>fill(id,load,view);}
  finally{clearTimeout(timer);}
 };
 await Promise.all([fill('home-stats',()=>api('overview'),stats=>`<div class="stats"><a class="stat accent" href="#repairs?status=active"><span>В работе</span><strong>${stats.repairs}</strong><small>${stats.overdue} с прошедшим сроком</small></a><a class="stat" href="#repairs?status=ready"><span>Готово к выдаче</span><strong>${stats.ready}</strong><small>Ремонт завершён</small></a>${manager()?`<a class="stat" href="#storage?status=active"><span>На хранении</span><strong>${stats.storage}</strong><small>${stats.storage_due} к выдаче в ближайшую неделю</small></a><a class="stat" href="#finance"><span>Принято сегодня</span><strong>${money(stats.today_payments)}</strong><small>Всего к оплате: ${money(stats.debt)}</small></a>`:`<a class="stat" href="#stock"><span>Мало на складе</span><strong>${stats.low_stock}</strong><small>Остаток до 2 штук</small></a>`}</div>`),fill('home-orders',()=>api('list',{kind:'repair',status:'active',limit:6}),list=>table(list.items,'repair'))]);
}
async function listPage(k,p,token){const page=k==='repair'?'repairs':'storage';const searchParams={...p,kind:k,status:p.status||'active',limit:50,offset:Number(p.offset)||0};const list=await api('list',searchParams);if(!mount(head(k==='repair'?'Ремонты':'Зимнее хранение',`${list.count} ${k==='repair'?'заказов':'приёмок'}`,manager()?`<a class="btn" href="${href('new',{kind:k})}">+ Новая приёмка</a>`:'')+`<form class="toolbar" id="filters"><input name="search" aria-label="Поиск приёмок" placeholder="Имя, телефон, модель, серийный номер" value="${esc(p.search||'')}"><select name="status" aria-label="Статус">${opts({active:'Только активные',all:'Все статусы',...statuses[k]},p.status||'active')}</select><button class="btn secondary">Найти</button><button type="button" class="btn ghost" id="export">Выгрузить в Excel</button></form><div class="board-controls"><nav class="view-switch" aria-label="Вид заказов"><a class="${p.view!=='board'?'':'active'}" href="${href(page,{...p,view:'board'})}" ${p.view==='board'?'aria-current="page"':''}>▦ Доска</a><a class="${p.view!=='board'?'active':''}" href="${href(page,{...p,view:'table'})}" ${p.view!=='board'?'aria-current="page"':''}>☷ Таблица</a></nav><span class="muted">Показано ${list.items.length} из ${list.count}</span></div>${p.view!=='board'?table(list.items,k):orderBoard(list.items,k)}${pagination(list.count,p.offset)}${k==='repair'&&manager()?'<a class="back" href="#legacy">Заказы прежнего сервиса</a>':''}`,token))return;
 $('filters').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(/^[\d+ ()-]+$/.test(data.search)&&data.search.replace(/\D/g,'').length>=6)data.search=data.search.replace(/\D/g,'').replace(/^8(?=\d{10}$)/,'7');go(page,{...data,view:p.view||'table'});};bindPagination(page,p,list.count);
 $('export').onclick=e=>run(e.currentTarget,async()=>{let items=[],offset=0,result;do{result=await api('list',{...searchParams,offset,limit:100});items.push(...result.items);offset+=100;}while(offset<result.count);csvDownload('FastGo-'+page+'-'+today()+'.csv',['Номер','Дата','ФИО','Телефон','Техника','Статус','Стоимость','Оплачено','Долг'],items.map(r=>[number(r,k),date(r.created_at),fio(r),r.phone,r.brand+' '+r.model,statuses[k][r.status],k==='repair'?r.total_amount:r.storage_amount,r.paid_amount,Number(k==='repair'?r.total_amount:r.storage_amount)-Number(r.paid_amount)]));toast('Выгрузка CSV для Excel готова');});}
async function clients(p,token){const data=await api('customers',p);if(!mount(head('Клиенты','История ремонтов и хранения по номеру телефона')+`<form id="client-search" class="toolbar"><input name="search" aria-label="Поиск клиента" placeholder="Имя или телефон" value="${esc(p.search||'')}"><button class="btn secondary">Найти</button></form><div class="panel flush">${data.items.length?`<table class="records"><thead><tr><th>Клиент</th><th>Техника</th><th>Приёмки</th><th>К оплате</th><th></th></tr></thead><tbody>${data.items.map(c=>`<tr><td><b>${esc(c.full_name)}</b><small>${esc(c.phone)}</small></td><td data-label="Техника">${esc(c.vehicles.join(', '))}</td><td data-label="Приёмки">${c.orders}<small>Последняя: ${date(c.last_visit)}</small></td><td data-label="К оплате">${money(c.debt)}</td><td class="wide"><div class="actions"><a class="btn ghost small" href="${href('repairs',{search:c.phone,status:'all'})}">Ремонты</a><a class="btn ghost small" href="${href('storage',{search:c.phone,status:'all'})}">Хранение</a></div></td></tr>`).join('')}</tbody></table>`:empty('Клиенты не найдены')}</div>${pagination(data.count,p.offset,100)}`,token))return;$('client-search').onsubmit=e=>{e.preventDefault();go('clients',Object.fromEntries(new FormData(e.target)));};bindPagination('clients',p,data.count,100);}
async function stock(p,token){const c=await catalog(),q=String(p.search||'').toLowerCase(),items=c.parts.filter(x=>(x.name+' '+(x.sku||'')+' '+(x.category||'')).toLowerCase().includes(q)&&(!p.low||x.quantity<=2));if(!mount(head('Склад',`${c.parts.length} позиций · остатки общей базы FastGo`,admin()?'<button class="btn" id="new-part">+ Запчасть</button>':'')+`<form class="toolbar" id="stock-search"><input name="search" aria-label="Поиск запчастей" placeholder="Название, модель или артикул" value="${esc(p.search||'')}"><select name="low" aria-label="Остатки">${opts({'':'Все остатки','yes':'Остаток до 2 шт.'},p.low||'')}</select><button class="btn secondary">Найти</button></form><div class="panel flush">${items.length?`<table class="records"><thead><tr><th>Запчасть</th><th>Категория</th><th>Остаток</th><th>Цена</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.name)}</b><small>${esc(x.sku||'Без артикула')}</small></td><td data-label="Категория">${esc(x.category||'—')}</td><td data-label="Остаток" class="amount ${x.quantity<=2?'debt':''}">${x.quantity} шт.</td><td data-label="Цена">${money(x.retail_price)}</td><td class="wide"><div class="actions">${manager()?`<button class="btn secondary small" data-stock="${x.id}">Движение</button>`:''}<button class="btn ghost small" data-history="${x.id}">История</button>${admin()?`<button class="btn ghost small" data-editpart="${x.id}">Править</button>`:''}</div></td></tr>`).join('')}</tbody></table>`:empty('Запчасти не найдены')}</div>`,token))return;
 $('stock-search').onsubmit=e=>{e.preventDefault();go('stock',Object.fromEntries(new FormData(e.target)));};if($('new-part'))$('new-part').onclick=()=>partModal();document.querySelectorAll('[data-editpart]').forEach(b=>b.onclick=()=>partModal(c.parts.find(x=>x.id===b.dataset.editpart)));document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>{const part=c.parts.find(x=>x.id===b.dataset.stock),request_id=crypto.randomUUID();modal(part.name,`<p class="muted">Сейчас: ${part.quantity} шт.</p><div class="field"><label for="movement_type">Операция</label><select name="movement_type" id="movement_type">${opts({receipt:'Поступление',issue:'Списание'})}</select></div>${field('quantity','Количество',1,'number',true)}${field('note','Основание / документ','','text',true)}`,async v=>{await api('stock',{...v,part_id:part.id,request_id});cache=null;toast('Движение сохранено');render();},()=>{document.querySelector('[name=quantity]').min=1;document.querySelector('[name=quantity]').step=1;});});
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>run(b,async()=>{const data=await api('stock_history',{part_id:b.dataset.history});modal('История движений',data.length?data.map(x=>`<div class="event"><b>${{receipt:'Поступление',issue:'Списание',return:'Возврат',adjustment:'Корректировка'}[x.movement_type]||esc(x.movement_type)} · ${x.quantity} шт.</b><div>${esc(x.note)}</div><small>${date(x.created_at)}</small></div>`).join(''):empty('Движений пока нет'));}));
}
function partModal(x={}){modal(x.id?'Изменить запчасть':'Новая запчасть',field('name','Название',x.name,'text',true)+field('sku','Артикул',x.sku)+field('category','Категория',x.category)+field('retail_price','Розничная цена, ₽',x.retail_price||0,'number',true)+'<p class="muted">Количество меняется через поступление или списание.</p>',async v=>{await api('part_save',{...v,id:x.id});cache=null;toast('Запчасть сохранена');render();},()=>{document.querySelector('[name=retail_price]').min=0;document.querySelector('[name=retail_price]').step='.01';});}
async function finance(p,token){const data=await api('finance',p);if(!mount(head('Оплаты','Принятые суммы и возвраты')+`<form class="toolbar" id="finance-filter">${field('from','С',p.from||today().slice(0,8)+'01','date')}${field('to','По',p.to||today(),'date')}<button class="btn secondary">Показать</button><button type="button" class="btn ghost" id="finance-export">Выгрузить в Excel</button></form><div class="stats">${[['Всего',data.total],['Наличные',data.cash],['Карта',data.card],['Перевод',data.transfer]].map(([n,v],i)=>`<div class="stat ${i===0?'accent':''}"><span>${n}</span><strong>${money(v)}</strong></div>`).join('')}</div><div class="panel flush">${data.items.length?`<table class="records"><thead><tr><th>Дата</th><th>Заказ</th><th>Способ</th><th>Сумма</th><th>Комментарий</th></tr></thead><tbody>${data.items.map(x=>`<tr><td>${date(x.created_at)}</td><td><a class="order-no" href="${href('order',{kind:x.repair_id?'repair':'storage',id:x.repair_id||x.storage_id})}">${x.repair_id?'Р':'Х'}-${String(x.repair_number||x.storage_number).padStart(4,'0')}</a></td><td data-label="Способ">${{cash:'Наличные',card:'Карта',transfer:'Перевод'}[x.method]}</td><td data-label="Сумма" class="amount">${money(x.amount)}</td><td data-label="Комментарий">${esc(x.note||'—')}</td></tr>`).join('')}</tbody></table>`:empty('За этот период оплат нет')}</div>${pagination(data.count,p.offset,100)}`,token))return;$('finance-filter').onsubmit=e=>{e.preventDefault();go('finance',Object.fromEntries(new FormData(e.target)));};bindPagination('finance',p,data.count,100);$('finance-export').onclick=e=>run(e.currentTarget,async()=>{let a=[],offset=0,d;do{d=await api('finance',{...p,offset});a.push(...d.items);offset+=100;}while(offset<d.count);csvDownload('FastGo-payments-'+today()+'.csv',['Дата','Ремонт','Хранение','Способ','Сумма','Комментарий'],a.map(x=>[date(x.created_at),x.repair_number,x.storage_number,{cash:'Наличные',card:'Карта',transfer:'Перевод'}[x.method],x.amount,x.note]));});}
function serviceGroup(x){
 if(x.category&&String(x.category).trim())return String(x.category).trim();
 const t=String(x.title||'').toLowerCase();
 if(/электр|диагност|аккумулятор|провод|контроллер|фар|дисплей/.test(t))return 'Электрические работы';
 if(/шин|камер|покрыш|колес/.test(t))return 'Шиномонтаж';
 if(/тормоз|колод|диск|трос/.test(t))return 'Тормозная система';
 if(/подшип|рулев|вилк|амортиз/.test(t))return 'Механические работы';
 return 'Монтаж и обслуживание';
}
async function pricePage(token){
 const c=await catalog(),groups=Object.groupBy?Object.groupBy(c.services,serviceGroup):c.services.reduce((g,x)=>{(g[serviceGroup(x)]||=[]).push(x);return g;},{});
 if(!mount(head('Прайс работ','Стоимость запчастей добавляется в заказ отдельно')+Object.entries(groups).map(([name,items])=>`<section class="panel flush"><div class="panelhead"><h2>${esc(name)}</h2></div><table class="records"><thead><tr><th>Работа</th><th>Цена работы</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.title)}</b>${x.pricing_note?`<small>${esc(x.pricing_note)}</small>`:''}</td><td data-label="Цена">${money(x.labor_price)}</td><td>${admin()?`<button class="btn ghost small" data-price="${x.id}">Редактировать</button>`:''}</td></tr>`).join('')}</tbody></table></section>`).join(''),token))return;
 document.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{const x=c.services.find(v=>v.id===b.dataset.price);modal('Редактировать работу',field('title','Название',x.title,'text',true)+field('category','Подраздел',serviceGroup(x),'text',true)+field('labor_price','Стоимость работы, ₽',x.labor_price,'number',true),async v=>{await api('catalog_save',{...v,id:x.id});cache=null;toast('Прайс обновлён');render();});});
}

async function staffPage(token){
 const c=await catalog(),staff=[...(c.staff||[])].sort((a,b)=>{
  const rank=x=>!x.active&&!x.approved_at?0:x.active?1:2;
  return rank(a)-rank(b)||String(a.name||'').localeCompare(String(b.name||''),'ru');
 }),pending=staff.filter(x=>!x.active&&!x.approved_at).length;
 const accessLabel=x=>!x.active&&!x.approved_at?'Новая заявка':x.active?'Активен':'Доступ отключён';
 const sub=pending?`${staff.length} сотрудников · ${pending} ждут доступа`:`${staff.length} сотрудников · права доступа и специализации`;
 if(!mount(head('Сотрудники',sub,'<button class="btn" id="add-staff">+ Сотрудник</button>')+`<div class="panel flush"><table class="records"><thead><tr><th>Сотрудник</th><th>Роль</th><th>Специализации</th><th>Доступ</th><th></th></tr></thead><tbody>${staff.map(x=>`<tr><td><b>${esc(x.name||'Без имени')}</b>${x.profile_id===me.profile_id?'<small>Это вы</small>':(!x.active&&!x.approved_at&&x.created_at?`<small>Заявка: ${date(x.created_at)}</small>`:'')}</td><td data-label="Роль">${esc(roles[x.role]||x.role)}</td><td data-label="Специализации">${esc((x.tags||[]).join(', ')||'—')}</td><td data-label="Доступ"><b>${accessLabel(x)}</b></td><td>${x.profile_id!==me.profile_id?`<div class="actions">${!x.active&&!x.approved_at?`<button class="btn small" data-approve="${x.profile_id}">Одобрить как мастер</button>`:''}<button class="btn ghost small" data-staff="${x.profile_id}">${!x.active&&!x.approved_at?'Настроить':'Редактировать'}</button></div>`:''}</td></tr>`).join('')}</tbody></table></div>`,token))return;
 const form=(x={},isnew=false)=>{
  const pendingRequest=!isnew&&!x.active&&!x.approved_at;
  const roleOpts=Object.fromEntries(Object.entries(roles).filter(([r])=>me.role==='owner'||r!=='owner').filter(([r])=>!isnew||r!=='owner'));
  const activeValue=pendingRequest?'true':String(x.active);
  modal(isnew?'Новый сотрудник':pendingRequest?'Рассмотреть заявку':'Доступ сотрудника',field('name','Имя',x.name,'text',true)+(isnew?field('email','Почта','','email',true)+field('password','Начальный пароль (от 12 символов)','','password',true):'')+`<div class="field"><label for="staff-role">Роль</label><select id="staff-role" name="role">${opts(roleOpts,x.role||'mechanic')}</select></div>`+field('tags','Специализации через запятую',(x.tags||[]).join(', '))+(!isnew?`<div class="field"><label for="staff-active">Доступ</label><select id="staff-active" name="active">${opts({true:'Активен',false:'Отключён'},activeValue)}</select></div>`:'<p class="muted">Передайте начальный пароль сотруднику лично. Письмо автоматически не отправляется.</p>'),async v=>{await api(isnew?'staff_create':'member_update',{...v,profile_id:x.profile_id,active:v.active!=='false',tags:v.tags.split(',').map(s=>s.trim()).filter(Boolean)});cache=null;toast(pendingRequest?'Доступ сотруднику выдан':'Сотрудник сохранён');render();});
 };
 $('add-staff').onclick=()=>form({},true);
 document.querySelectorAll('[data-staff]').forEach(b=>b.onclick=()=>form(staff.find(x=>x.profile_id===b.dataset.staff)));
 document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>run(b,async()=>{
  const x=staff.find(s=>s.profile_id===b.dataset.approve);
  if(!x)return;
  await api('member_update',{profile_id:x.profile_id,name:x.name||'Сотрудник',role:'mechanic',active:true,tags:x.tags||[]});
  cache=null;toast('Доступ выдан: роль «Мастер»');render();
 }));
}
const OWNER_DEVICE_KEY='fastgo_owner_device_v1';
function ownerDeviceToken(create=false){
 let value='';try{value=localStorage.getItem(OWNER_DEVICE_KEY)||'';}catch{}
 if(!value&&create){value=crypto.randomUUID();try{localStorage.setItem(OWNER_DEVICE_KEY,value);}catch{throw new Error('Safari не дал сохранить привязку устройства');}}
 return value;
}
async function accountPage(token){
 let device=null;
 if(me.role==='owner'){
  let deviceToken=ownerDeviceToken(false);
  device=await api('owner_device_status',{device_token:deviceToken},{fresh:true});
  if(!device.registered&&device.can_enroll&&/iPhone/i.test(navigator.userAgent)){
   deviceToken=ownerDeviceToken(true);
   device=await api('owner_device_enroll',{device_token:deviceToken});
  }
 }
 const ownerPanel=me.role==='owner'?(device?.trusted?`<section class="panel"><h2>Пароль владельца</h2><p class="muted">Доверенное устройство: ${esc(device.label||'iPhone 13')}. Этот блок показывается только на привязанном iPhone.</p><button class="btn" id="owner-password">Сменить пароль владельца</button></section>`:`<section class="panel"><h2>Аккаунт владельца</h2><p class="muted">${device?.registered?'Этот браузер не является доверенным iPhone 13 владельца.':'Доверенный iPhone владельца ещё не привязан.'}</p></section>`):'';
 const staffPanel=me.role!=='owner'?`<section class="panel"><h2>Учётная запись сотрудника</h2><p class="muted">Текущий логин: ${esc(me.email||'—')}</p><form id="login-change"><div class="grid">${field('email','Новый логин / email',me.email||'','email',true)}</div><button class="btn secondary">Сменить логин</button></form><div style="height:14px"></div><button class="btn" id="staff-password">Сменить пароль</button><p class="muted">Для смены пароля FastGo отправит защищённую ссылку на вашу подтверждённую почту.</p></section>`:'';
 if(!mount(head('Аккаунт','Логин и безопасность')+`<section class="panel"><div class="info"><div><label>Сотрудник</label><p>${esc(me.name||'—')}</p></div><div><label>Роль</label><p>${esc(roles[me.role]||me.role)}</p></div><div><label>Логин</label><p>${esc(me.email||'—')}</p></div></div></section>${ownerPanel}${staffPanel}`,token))return;
 if($('owner-password'))$('owner-password').onclick=e=>run(e.currentTarget,async()=>{await api('account_recovery',{device_token:ownerDeviceToken(false)});toast('Ссылка для смены пароля отправлена на почту владельца');});
 if($('staff-password'))$('staff-password').onclick=e=>run(e.currentTarget,async()=>{await api('account_recovery');toast('Ссылка для смены пароля отправлена на вашу почту');});
 if($('login-change'))$('login-change').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const v=Object.fromEntries(new FormData(e.currentTarget));await api('account_email_change',{email:v.email});toast('Запрос на смену логина отправлен. Проверьте новую почту.');});};
}
async function settings(token){const l=await api('legal');if(!mount(head('Реквизиты','Данные исполнителя для печатных документов')+`<form id="legal-form" class="panel"><div class="grid">${[['legal_name','Наименование'],['full_name','ФИО'],['inn','ИНН'],['ogrnip','ОГРНИП'],['registration_address','Адрес'],['phone','Телефон'],['email','Email'],['bank_name','Банк'],['bik','БИК'],['correspondent_account','Корреспондентский счёт'],['settlement_account','Расчётный счёт']].map(([n,label])=>field(n,label,l?.[n]||'','text',n==='legal_name')).join('')}</div><div id="legal-error" role="alert"></div><button class="btn">Сохранить реквизиты</button></form>`,token))return;$('legal-form').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{await api('legal_save',Object.fromEntries(new FormData(e.target)));toast('Реквизиты сохранены');});};}
async function legacy(token){const orders=await api('legacy');mount(head('Прежние сервисные заказы','Записи, созданные в сервисе до объединения приложения')+(orders.length?orders.map(x=>`<section class="panel"><h2>${esc(x.order_code)}</h2><div class="info"><div><label>Клиент</label><p>${esc(x.full_name)} · ${esc(x.phone)}</p></div><div><label>Техника</label><p>${esc(x.brand)} ${esc(x.model)}</p></div><div><label>Неисправность</label><p>${esc(x.reason)}</p></div><div><label>Состояние заказа</label><p>${esc(({awaiting_assignment:'Ожидает назначения',in_repair:'В ремонте',completed:'Завершён',closed:'Закрыт'})[x.status]||x.status)}</p></div></div><h3 style="margin-top:20px">Работы</h3>${x.items.map(i=>`<p>${esc(i.title)} · ${i.quantity} × ${money(Number(i.parts_price)+Number(i.labor_price))}</p>`).join('')}<p><b>Итого: ${money(x.final_price??x.estimated_price)}</b></p>${x.new_repair_id?`<a class="btn" href="${href('order',{kind:'repair',id:x.new_repair_id})}">Продолжен как ремонт № ${x.new_repair_number}</a>`:!['closed','cancelled'].includes(x.status)?`<button class="btn" data-import-legacy="${x.id}">Продолжить в мастерской</button>`:''}</section>`).join(''):empty('Прежних заказов нет')),token);if(token!==epoch)return;document.querySelectorAll('[data-import-legacy]').forEach(b=>b.onclick=()=>modal('Продолжить прежний заказ','<p>В новую карточку будут перенесены клиент, техника, неисправность и стоимость. Исходная запись останется доступна для просмотра. Прежний бот не синхронизирует дальнейшие изменения новой карточки.</p>',async()=>{const r=await api('import_legacy',{id:b.dataset.importLegacy});toast('Заказ перенесён');go('order',{kind:'repair',id:r.id});}));}
const ctx={get me(){return me;},get token(){return epoch;},get dirty(){return dirty;},mount,head,field,modal,run,toast,go,href,catalog,admin,manager,empty,refresh:render,setDirty:v=>dirty=v};
async function render(){const token=++epoch;const {page,p}=route();currentPage=page==='order'||page==='new'||page==='document'?(p.kind==='storage'?'storage':'repairs'):page;if(!me){if(!sessionAvailable()){login();return;}try{const access=await api('request_access',{}, {fresh:true});if(!access.active){pendingAccess();return;}me=await api('me');}catch(e){login(e.message);return;}}
 if(!manager()&&['storage','clients','finance','legacy','new'].includes(page)||!admin()&&page==='staff'||me.role!=='owner'&&page==='settings'){mount(empty('Этот раздел недоступен вашей роли'),token);return;}
 clearTimeout(loadingTimer);loadingTimer=setTimeout(()=>{const label=page==='new'?'Приёмка':nav.find(x=>x[0]===currentPage)?.[1]||'Заказ';const action=manager()&&['repairs','storage'].includes(page)?`<a class="btn" href="#new?kind=${page==='storage'?'storage':'repair'}">+ Новая приёмка</a>`:'';mount(head(label,'',action)+'<div class="panel" role="status">Загружаем данные…</div>',token);},120);dirty=false;
 try{if(page==='home')await home(token);else if(page==='repairs'||page==='storage')await listPage(page==='storage'?'storage':'repair',p,token);else if(page==='new')await renderIntake(ctx,p,token);else if(page==='order')await renderDetail(ctx,p,token);else if(page==='document')await renderDocument(ctx,p,token);else if(page==='clients')await clients(p,token);else if(page==='stock')await stock(p,token);else if(page==='finance')await finance({from:today().slice(0,8)+'01',to:today(),...p},token);else if(page==='catalog')await pricePage(token);else if(page==='staff')await staffPage(token);else if(page==='account')await accountPage(token);else if(page==='settings')await settings(token);else if(page==='legacy')await legacy(token);else go('home');}catch(e){if(token===epoch&&me){mount(`<div class="error" role="alert">${esc(e.message)}</div><button class="btn secondary" id="retry">Попробовать снова</button>`,token);$('retry').onclick=()=>{invalidateReads();render();};}}finally{if(token===epoch)clearTimeout(loadingTimer);}}
window.addEventListener('workshop-auth-required',()=>{epoch++;cache=null;login('Сессия истекла. Войдите снова.');});let lastHash=location.hash;window.addEventListener('hashchange',()=>{if(dirty&&!confirm('Есть несохранённые изменения. Перейти без сохранения?')){history.replaceState(null,'',lastHash||'#home');return;}dirty=false;lastHash=location.hash;render();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a&&dirty){if(!confirm('Есть несохранённые изменения. Перейти без сохранения?'))e.preventDefault();else dirty=false;}});render();

window.addEventListener('workshop-data-changed',()=>{const before=epoch;setTimeout(()=>{if(me&&epoch===before&&!dirty&&['home','stock','repairs','storage','finance'].includes(route().page)&&!document.querySelector('dialog[open]'))render();},100);});
