import {api,esc,money,csvDownload,today} from './core.js';
import {openSales} from './inventory-ui.js';
const $=id=>document.getElementById(id);
const stamp=v=>v?new Date(v).toLocaleString('ru-RU',{timeZone:'Asia/Yekaterinburg'}):'—';
export async function renderCash(ctx,p,token){
 const data=await api('cash_state',p,{fresh:true}),s=data.selected,t=data.totals;
 const options=data.shifts.map(x=>`<option value="${esc(x.id)}" ${x.id===s?.id?'selected':''}>${esc(x.register)} · №${x.number} · ${x.status==='open'?'Открыта':'Закрыта'} · ${stamp(x.opened_at)}</option>`).join('');
 if(!ctx.mount(`<div class="pagehead"><div><h1>Кассы и продажи</h1><p class="muted">Товарные продажи за смену. Оплаты ремонта и хранения — в разделе «Оплаты».</p></div><button class="btn secondary" id="cash-open">Открыть смену</button></div><div class="toolbar"><label for="cash-shift">Касса и смена</label><select id="cash-shift" ${options?'':'disabled'}>${options||'<option>Нет смен</option>'}</select><button class="btn ghost" id="cash-refresh">Обновить</button></div>${s?`<section class="panel"><div class="panelhead"><div><h2>${esc(s.register)} · смена №${s.number}</h2><p>${s.status==='open'?'Открыта':'Закрыта'} · ${stamp(s.opened_at)}${s.closed_at?' — '+stamp(s.closed_at):''}</p><p class="muted">Открыл: ${esc(s.cashier)}</p></div><div class="actions">${s.status==='open'?'<button class="btn" id="cash-sale">Сканировать / продать</button><button class="btn secondary" id="cash-close">Закрыть смену</button>':''}<button class="btn ghost" id="cash-export">Выгрузить смену</button></div></div><div class="stats">${[['Наличные',t.cash],['Безнал',t.cashless],['Итого за смену',t.total]].map(([label,n])=>`<div class="stat"><span>${label}</span><strong>${money(n)}</strong></div>`).join('')}</div><p>${t.count} продаж · Карта: ${money(t.card)} · Перевод: ${money(t.transfer)}</p><p>На начало: ${money(s.opening_cash)} · Наличных должно быть: <b>${money(t.expected_cash)}</b></p>${s.closing?`<p>Пересчитано: ${money(s.closing.counted_cash)} · Расхождение: <b>${money(s.closing.difference)}</b></p><p class="muted">Закрыл: ${esc(s.closing.cashier)}. ${esc(s.closing.note)}</p>`:''}</section><section class="panel flush">${data.sales.length?`<table class="records"><thead><tr><th>Продажа</th><th>Время</th><th>Оплата</th><th>Сумма</th><th>Сотрудник</th></tr></thead><tbody>${data.sales.map(x=>`<tr><td data-label="Продажа">${esc(x.sale_number)}</td><td data-label="Время">${stamp(x.created_at)}</td><td data-label="Оплата">${esc(x.payment_method)}</td><td data-label="Сумма">${money(x.total)}</td><td data-label="Сотрудник">${esc(x.cashier_id)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">В этой смене продаж пока нет</div>'}</section><div class="actions"><button class="btn ghost" id="cash-prev" ${data.offset===0?'disabled':''}>Назад</button><span>${data.offset+1}–${Math.min(data.offset+100,t.count)} из ${t.count}</span><button class="btn ghost" id="cash-next" ${data.offset+100>=t.count?'disabled':''}>Далее</button></div>`:'<div class="empty"><strong>Откройте первую смену</strong><p>Укажите кассу и сумму наличных на начало.</p></div>'}<p class="muted">Эвотор пока не подключён. Проведение продажи здесь учитывает товар и оплату, но не печатает фискальный чек.</p>`,token))return;
 const go=(shift,offset=0)=>ctx.go('cash',{shift_id:shift,offset});
 $('cash-refresh').onclick=()=>ctx.go('cash',p);
 $('cash-shift').onchange=e=>go(e.target.value);
 $('cash-open').onclick=()=>ctx.modal('Открыть смену','<div class="field"><label for="cash-name">Название кассы</label><input id="cash-name" name="register" value="Основная касса" maxlength="80" required></div><div class="field"><label for="cash-opening">Наличные на начало, ₽</label><input id="cash-opening" name="opening_cash" type="number" min="0" step="0.01" value="0" required></div>',async v=>{const r=await api('shift_open',{register:v.register,opening_cash:Number(v.opening_cash)});go(r.id);});
 if(!s)return;
 $('cash-prev').onclick=()=>go(s.id,Math.max(0,data.offset-100));$('cash-next').onclick=()=>go(s.id,data.offset+100);
 if($('cash-sale'))$('cash-sale').onclick=e=>ctx.run(e.currentTarget,()=>openSales(s.id));
 if($('cash-close'))$('cash-close').onclick=()=>ctx.modal('Закрыть смену №'+s.number,`<p>Продажи: <b>${money(t.total)}</b>. Наличных должно быть: <b>${money(t.expected_cash)}</b>.</p><p>Пересчитайте деньги. После закрытия новые продажи в эту смену не принимаются.</p><div class="field"><label for="cash-count">Фактически наличных, ₽</label><input id="cash-count" name="counted_cash" type="number" min="0" step="0.01" required></div><div class="field"><label for="cash-note">Комментарий</label><input id="cash-note" name="note" maxlength="500"></div>`,async v=>{await api('shift_close',{shift_id:s.id,counted_cash:Number(v.counted_cash),note:v.note});go(s.id);});
 $('cash-export').onclick=e=>ctx.run(e.currentTarget,async()=>{let rows=[],offset=0,d;do{d=await api('cash_state',{shift_id:s.id,offset},{fresh:true});rows.push(...d.sales);offset+=100;}while(offset<d.totals.count);csvDownload('FastGo-смена-'+s.number+'-'+today()+'.csv',['Касса','Смена','Продажа','Дата','Оплата','Сумма','Сотрудник'],rows.map(x=>[s.register,s.number,x.sale_number,stamp(x.created_at),x.payment_method,x.total,x.cashier_id]));});
}
