import {api,esc,money} from './core.js';
import {equipmentTypes,equipmentType,filterEquipment} from './equipment-core.js';
import {newPartForm,openSales,printPartLabel,bindProductPreviews} from './inventory-ui.js';
export async function renderEquipment(ctx,p,token){
 const c=await api('catalog',{}, {fresh:true});
 const items=filterEquipment(c.parts||[],{search:p.search||'',type:p.type||'',available:p.available==='yes'});
 const sell=['developer','owner','seller'].includes(ctx.me.role);
 const canReceive=['developer','owner','seller'].includes(ctx.me.role);
 const types=equipmentTypes.map(t=>`<option value="${esc(t)}" ${p.type===t?'selected':''}>${esc(t)}</option>`).join('');
 const actions=(ctx.admin()?'<button class="btn" id="equipment-add">+ Добавить технику</button> ':'')+(canReceive?'<a class="btn secondary" href="#stock-receive">Приход списком</a>':'');
 if(!ctx.mount(ctx.head('Техника','Техника для продажи · цены и остатки общего склада',actions)+`<form class="toolbar" id="equipment-filter"><input name="search" aria-label="Поиск техники" placeholder="Название, модель, артикул, штрихкод" value="${esc(p.search||'')}"><select name="type" aria-label="Тип техники"><option value="">Вся техника</option>${types}</select><select name="available" aria-label="Наличие"><option value="">Все остатки</option><option value="yes" ${p.available==='yes'?'selected':''}>В наличии</option></select><button class="btn secondary">Найти</button></form><div class="panel flush">${items.length?`<table class="records"><thead><tr><th>Техника</th><th>Тип</th><th>Остаток</th><th>Цена</th><th>Действия</th></tr></thead><tbody>${items.map(x=>`<tr><td data-label="Техника">${c.capabilities?.private_product_photos?`<button type="button" class="product-photo-thumb" data-product-photo="${esc(x.id)}" aria-label="Фото товара: ${esc(x.name)}">Фото</button>`:''}<b>${esc(x.name)}</b><small>${esc([x.model,x.sku,x.barcode].filter(Boolean).join(' · '))}</small></td><td data-label="Тип">${esc(equipmentType(x))}</td><td data-label="Остаток">${Number(x.quantity)||0} шт.</td><td data-label="Цена">${money(x.retail_price)}</td><td><div class="actions">${sell?`<button class="btn small" data-equipment-sell="${esc(x.id)}" ${Number(x.quantity)>0?'':'disabled'}>Продать</button>`:''}${ctx.admin()?`<button class="btn ghost small" data-equipment-edit="${esc(x.id)}">Изменить</button>`:''}<button class="btn ghost small" data-equipment-label="${esc(x.id)}">Этикетка</button></div></td></tr>`).join('')}</tbody></table>`:ctx.empty('Техники пока нет или ничего не найдено','<p>Добавьте модель, цену и количество. Реальные товары появятся здесь после приёмки.</p>')}</div><p class="muted">Продажа проводится в открытой кассовой смене и уменьшает остаток техники.</p>`,token))return;
 bindProductPreviews(document.getElementById('workspace'),items);
 document.getElementById('equipment-filter').onsubmit=e=>{e.preventDefault();ctx.go('equipment',Object.fromEntries(new FormData(e.target)));};
 const add=document.getElementById('equipment-add');if(add)add.onclick=()=>ctx.run(add,async()=>{await newPartForm('',{equipment:true});document.getElementById('inventory-dialog').addEventListener('close',()=>{if(location.hash.startsWith('#equipment'))ctx.refresh();},{once:true});});
 document.querySelectorAll('[data-equipment-sell]').forEach(b=>b.onclick=()=>ctx.run(b,()=>openSales(undefined,b.dataset.equipmentSell)));
 document.querySelectorAll('[data-equipment-label]').forEach(b=>b.onclick=()=>ctx.run(b,()=>printPartLabel(items.find(x=>x.id===b.dataset.equipmentLabel))));
 document.querySelectorAll('[data-equipment-edit]').forEach(b=>b.onclick=()=>{
  const x=items.find(x=>x.id===b.dataset.equipmentEdit);
  ctx.modal('Изменить технику',ctx.field('name','Наименование',x.name,'text',true)+ctx.field('model','Модель',x.model)+ctx.field('sku','Артикул',x.sku)+`<div class="field"><label for="equipment-type">Тип техники</label><select name="type" id="equipment-type">${equipmentTypes.map(t=>`<option ${equipmentType(x)===t?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`+ctx.field('retail_price','Цена продажи, ₽',x.retail_price,'number',true),async v=>{await api('part_save',{id:x.id,name:v.name,model:v.model,sku:v.sku,category:'Техника · '+v.type,retail_price:Number(v.retail_price),request_id:crypto.randomUUID()});ctx.toast('Техника обновлена');ctx.refresh();},()=>{const price=document.querySelector('[name=retail_price]');price.min='0';price.step='0.01';});
 });
}
