from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
def functions(path):
 text=path.read_text();matches=list(re.finditer(r'^function (\w+)\(',text,re.M));return {m.group(1):text[m.start():matches[i+1].start() if i+1<len(matches) else len(text)].strip() for i,m in enumerate(matches)}
a=functions(root/'google-apps-script/Code.gs');b=functions(root/'google-apps-script/Reliability.gs')
excluded={'doGet','doPost','route_','ss_','sh_','rows_','headers_','append_','patchRow_','uid_','now_','json_','upload_','documents_','signedUrl_'}
code='\n\n'.join(v for k,v in a.items() if k not in excluded)
code=re.sub(r"  const root=DriveApp.getFolderById.*?assertPrivate_\(folder\);", "  const folderUrl='', created=now_();",code)
code=code.replace("'Работа, ₽':num_(p.labor_price),updated_at", "'Работа, ₽':num_(p.labor_price),'Итого, ₽':num_(p.labor_price)+num_(r['Запчасти, ₽']),updated_at")
extra='\n\n'.join(b[n] for n in ['assertOpen_','validateOrderUpdate_','partPhotoPrimary_','partPhotos_','migrationManifest_'])
# These declarations are pure business rules from the production Google engine.
# The adapter owns persistence and commits the complete write set atomically.
prefix=(root/'scripts/native-engine-prefix.txt').read_text()
suffix=(root/'scripts/native-engine-suffix.txt').read_text()
(root/'supabase/functions/_shared/native-engine.js').write_text('// Generated by scripts/build-native-engine.py.\n'+prefix+'\n'+code+'\n'+extra+'\n'+suffix)
