begin;

create extension if not exists pgcrypto;

do $$ begin
  create type stock_movement_type as enum ('receipt','issue','adjustment','return');
exception when duplicate_object then null;
end $$;

create sequence if not exists part_barcode_seq start 1;
create sequence if not exists inventory_category_barcode_seq start 1;
create sequence if not exists workshop_sale_number_seq start 1;

create table if not exists workshop_members (
  profile_id uuid primary key,
  name text not null default '',
  role text not null check(role in ('owner','admin','receiver','manager','mechanic')),
  active boolean not null default true,
  tags text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists storage_intakes (
  id uuid primary key default gen_random_uuid(),
  storage_number bigint generated by default as identity unique,
  qr_token uuid not null default gen_random_uuid() unique,
  last_name text not null,
  first_name text not null,
  middle_name text,
  phone text not null,
  email text,
  brand text not null,
  model text not null,
  serial_number text,
  scooter_photo_path text,
  display_photo_path text,
  motor_photo_path text,
  issue_description text,
  accessories text,
  condition_notes text,
  storage_location text,
  planned_return_date date,
  status text not null default 'accepted' check(status in ('accepted','stored','ready_return','returned','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  fault_photo_paths jsonb not null default '[]'::jsonb,
  storage_tariff text,
  storage_months integer,
  storage_amount numeric(12,2),
  signed_document_paths jsonb not null default '[]'::jsonb,
  documents_uploaded_at timestamptz,
  starts_on date,
  wash boolean not null default false,
  paid_amount numeric(12,2) not null default 0,
  revision integer not null default 1,
  request_id uuid unique,
  issued_at timestamptz,
  handover_notes text,
  extension_months integer not null default 0,
  extension_amount numeric(12,2) not null default 0
);

create table if not exists service_repairs (
  id uuid primary key default gen_random_uuid(),
  repair_number bigint generated by default as identity unique,
  qr_token uuid not null default gen_random_uuid() unique,
  last_name text not null,
  first_name text not null,
  middle_name text,
  phone text not null,
  email text,
  vehicle_type text not null default 'Электросамокат',
  brand text not null,
  model text not null,
  serial_number text,
  issue_description text,
  condition_notes text,
  accessories text,
  scooter_photo_path text,
  display_photo_path text,
  motor_photo_path text,
  fault_photo_paths jsonb not null default '[]'::jsonb,
  diagnostics_notes text,
  assigned_master text,
  status text not null default 'accepted' check(status in ('accepted','diagnostics','waiting_parts','repair','ready','issued','cancelled')),
  works jsonb not null default '[]'::jsonb,
  parts jsonb not null default '[]'::jsonb,
  labor_amount numeric(12,2) not null default 0,
  parts_amount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  promised_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  assigned_master_id uuid,
  paid_amount numeric(12,2) not null default 0,
  revision integer not null default 1,
  request_id uuid unique,
  approved_amount numeric(12,2),
  approval_note text,
  quality_checked boolean not null default false,
  issued_at timestamptz,
  handover_notes text,
  signed_document_paths jsonb not null default '[]'::jsonb,
  documents_uploaded_at timestamptz,
  storage_id uuid references storage_intakes(id),
  tags text[] not null default '{}',
  legacy_order_id uuid unique
);

create table if not exists service_catalog (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  category text not null,
  wheel_position text,
  service_kind text not null,
  title text not null,
  parts_price numeric(12,2) not null default 0,
  labor_price numeric(12,2) not null default 0,
  total_price numeric(12,2),
  aliases text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  labor_price_max numeric(12,2),
  pricing_note text
);

create table if not exists parts (
  id uuid primary key default gen_random_uuid(),
  sku text,
  name text not null,
  quantity integer not null default 0 check(quantity >= 0),
  unit_cost numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  category text,
  aliases text[] not null default '{}',
  specs jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  retail_price numeric(12,2) not null default 0,
  price_note text,
  barcode text not null unique default ('FGP-' || lpad(nextval('part_barcode_seq')::text,8,'0')),
  model text,
  unit text not null default 'шт',
  active boolean not null default true,
  primary_photo_path text
);

create table if not exists inventory_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  barcode text not null unique default ('FGC-' || lpad(nextval('inventory_category_barcode_seq')::text,6,'0')),
  primary_photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists workshop_payments (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique,
  repair_id uuid references service_repairs(id),
  storage_id uuid references storage_intakes(id),
  amount numeric(12,2) not null check(amount <> 0),
  method text not null check(method in ('cash','card','transfer')),
  note text not null default '',
  actor_id uuid not null,
  created_at timestamptz not null default now(),
  check(num_nonnulls(repair_id,storage_id)=1)
);

create table if not exists workshop_events (
  id bigint generated always as identity primary key,
  kind text not null,
  record_id uuid not null,
  action text not null,
  actor_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists workshop_sales (
  id uuid primary key default gen_random_uuid(),
  sale_number bigint not null unique default nextval('workshop_sale_number_seq'),
  request_id uuid not null unique,
  cashier_id uuid not null,
  payment_method text not null check(payment_method in ('cash','card','transfer')),
  total numeric(12,2) not null default 0 check(total >= 0),
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists workshop_sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references workshop_sales(id) on delete cascade,
  part_id uuid not null references parts(id),
  quantity integer not null check(quantity > 0),
  unit_price numeric(12,2) not null check(unit_price >= 0),
  line_total numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now()
);

create table if not exists stock_movements (
  id uuid primary key default gen_random_uuid(),
  part_id uuid not null references parts(id),
  movement_type stock_movement_type not null,
  quantity integer not null check(quantity > 0),
  maintenance_order_id uuid,
  actor_id uuid,
  note text,
  created_at timestamptz not null default now(),
  service_stock_receipt_id uuid,
  service_sales_report_id uuid,
  workshop_repair_id uuid references service_repairs(id),
  workshop_request_id uuid unique,
  workshop_sale_id uuid references workshop_sales(id)
);

create table if not exists legal_entity_settings (
  id smallint primary key default 1 check(id=1),
  entity_type text not null default 'individual_entrepreneur',
  legal_name text not null,
  full_name text,
  inn text,
  ogrnip text,
  registration_address text,
  bank_name text,
  bik text,
  correspondent_account text,
  settlement_account text,
  phone text,
  email text,
  notes text,
  updated_at timestamptz not null default now()
);

create index if not exists workshop_repairs_assignee on service_repairs(assigned_master_id,status);
create index if not exists workshop_repairs_created on service_repairs(created_at desc);
create index if not exists workshop_repairs_storage on service_repairs(storage_id);
create index if not exists workshop_storage_due on storage_intakes(status,planned_return_date);
create index if not exists workshop_payments_repair on workshop_payments(repair_id,created_at);
create index if not exists workshop_payments_storage on workshop_payments(storage_id,created_at);
create index if not exists workshop_events_record on workshop_events(kind,record_id,created_at desc);
create index if not exists parts_category_model_idx on parts(category,model);
create index if not exists parts_active_idx on parts(active) where active;
create index if not exists stock_movements_part on stock_movements(part_id,created_at desc);
create index if not exists stock_movements_repair on stock_movements(workshop_repair_id);
create index if not exists stock_movements_sale on stock_movements(workshop_sale_id);
create index if not exists workshop_sales_created on workshop_sales(created_at desc);

create or replace function apply_stock_movement()
returns trigger language plpgsql set search_path=public,pg_temp as $$
begin
  if new.movement_type in ('receipt','return') then
    update parts set quantity=quantity+new.quantity,updated_at=now() where id=new.part_id;
  elsif new.movement_type='issue' then
    update parts set quantity=quantity-new.quantity,updated_at=now() where id=new.part_id and quantity>=new.quantity;
    if not found then raise exception 'Insufficient stock'; end if;
  end if;
  return new;
end $$;

drop trigger if exists stock_movement_apply on stock_movements;
create trigger stock_movement_apply after insert on stock_movements for each row execute function apply_stock_movement();

create or replace function workshop_sale(p_actor uuid,p jsonb)
returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $$
declare m workshop_members;s workshop_sales;item jsonb;pr parts;req uuid;pid uuid;qty integer;total_amount numeric(12,2):=0;sale_items jsonb:='[]'::jsonb;
begin
  select * into m from workshop_members where profile_id=p_actor and active;
  if not found or m.role not in ('owner','admin','receiver','manager') then raise exception 'Нет права проводить продажи'; end if;
  req:=nullif(p->>'request_id','')::uuid;if req is null then raise exception 'Нет ключа операции';end if;
  perform pg_advisory_xact_lock(hashtextextended(req::text,0));
  select * into s from workshop_sales where request_id=req;
  if found then return jsonb_build_object('id',s.id,'sale_number',s.sale_number,'total',s.total,'duplicate',true); end if;
  if p->>'payment_method' not in ('cash','card','transfer') then raise exception 'Выберите способ оплаты';end if;
  if jsonb_typeof(p->'items')<>'array' or jsonb_array_length(p->'items')<1 then raise exception 'Корзина пуста';end if;
  insert into workshop_sales(request_id,cashier_id,payment_method,note) values(req,p_actor,p->>'payment_method',left(coalesce(p->>'note',''),500)) returning * into s;
  for item in select value from jsonb_array_elements(p->'items') loop
    pid:=nullif(item->>'part_id','')::uuid;qty:=coalesce((item->>'quantity')::integer,0);
    if pid is null or qty<1 then raise exception 'Проверьте товар и количество';end if;
    select * into pr from parts where id=pid and active for update;
    if not found then raise exception 'Товар не найден или отключён';end if;
    if pr.quantity<qty then raise exception 'Недостаточно товара: % (остаток %)',pr.name,pr.quantity;end if;
    insert into workshop_sale_items(sale_id,part_id,quantity,unit_price) values(s.id,pr.id,qty,pr.retail_price);
    insert into stock_movements(part_id,movement_type,quantity,actor_id,note,workshop_sale_id) values(pr.id,'issue',qty,p_actor,'Продажа №'||s.sale_number,s.id);
    total_amount:=total_amount+qty*pr.retail_price;
    sale_items:=sale_items||jsonb_build_array(jsonb_build_object('part_id',pr.id,'name',pr.name,'barcode',pr.barcode,'quantity',qty,'unit_price',pr.retail_price,'line_total',qty*pr.retail_price));
  end loop;
  update workshop_sales set total=total_amount where id=s.id returning * into s;
  insert into workshop_events(kind,record_id,action,actor_id,details) values('sale',s.id,'completed',p_actor,jsonb_build_object('sale_number',s.sale_number,'total',s.total,'payment_method',s.payment_method));
  return jsonb_build_object('id',s.id,'sale_number',s.sale_number,'total',s.total,'items',sale_items,'duplicate',false);
end $$;

commit;
